---
apiVersion: v1
kind: Namespace
metadata:
  name: telemetry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-service
  namespace: telemetry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vector-service
  template:
    metadata:
      labels:
        app: vector-service
    spec:
      containers:
        - name: vector-service
          image: timberio/vector:latest-alpine
          command: ["vector"]
          args: 
            - "--config"
            - "/etc/vector/vector.toml"
            - "--verbose"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: vector-config
              mountPath: /etc/vector/
            - name: vector-data
              mountPath: "/var/lib/vector"
      volumes:
        - name: vector-config
          configMap:
            name: vector-service-config
        - name: vector-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: telemetry
spec:
  selector:
    app: vector-service
  ports:
    - protocol: TCP
      port: 5000
---
