---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-with-vector-sidecar
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-with-vector-sidecar
  template:
    metadata:
      labels:
        app: app-with-vector-sidecar
    spec:
      containers:
        - name: app
          image: "subfuzion/netcat"
          command: [ "sh", "-c"]
          args:
            - while true; do
                echo -en '\nHello World';
                sleep 10;
              done;
        # this should be injected via a web hook
        - name: vector
          image: timberio/vector:latest-alpine
          command: ["vector"]
          args: 
            - "--config"
            - "/etc/vector/vector.toml"
            - "--verbose"
            - "--require-healthy"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: vector-config
              mountPath: /etc/vector/
            - name: vector-data
              mountPath: "/var/lib/vector"
            - name: dockersock
              mountPath: "/var/run/docker.sock"
      volumes:
        - name: vector-config
          configMap:
            name: vector-sidecar-config
        - name: vector-data
          emptyDir: {}
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
---